### ISSUE TITLE
500 error for bridge-synth-index-nomics

### ISSUE THREAD

**Issue by rstormsf** [smartcontractkit/external-adapters-js#123]
Test:
```
curl -X POST -H "Content-Type: application/json" --data '{"id": 123, "data": { "from": "sCEX", "to": "USD" }}' http://bridge:1247
```
result
```json
{
  "jobRunID": 123,
  "status": "errored",
  "error": {
    "error": {
      "name": "AdapterError",
      "message": "Cannot read property 'price' of undefined"
    }
  },
  "statusCode": 500
}
```

code: https://github.com/smartcontractkit/external-adapters-js/blob/master/synth-index/nomics/priceAdapter.js#L28

**Comment by thodges-gh** [comment]
My steps (just using Docker locally to test this easily):
- `make docker-synth-index adapter=nomics`
- `docker run -it -p 8080:8080 -e API_KEY=my_api_key synth-index-nomics-adapter:latest`
- Success: `curl -X POST -H 'content-type: application/json' -d '{"data":{"asset":"sDEFI"}}' http://localhost:8080`
- Fail: `curl -X POST -H 'content-type: application/json' -d '{"data":{"asset":"sCEX"}}' http://localhost:8080`

It looks like the cause is Nomics "fixed" their support for the LEO token. They used to only accept the symbol "LEOTOKEN" instead of "LEO", now they accept "LEO" but didn't implement backwards-compatibility with the old "LEOTOKEN" symbol. I'll get a quick PR up to fix this shortly.
