### ISSUE TITLE
Generate adapter documentation automatically

### ISSUE THREAD

**Issue by krebernisak** [smartcontractkit/external-adapters-js#413]
Keeping documentation up to date for adapters is painful, and we should be looking at how to automate this process.

The discussion on the topic [started here](https://github.com/smartcontractkit/external-adapters-js/pull/403#pullrequestreview-626907588).

**Comment by aalu1418** [comment]
Adding a few notes from some research on automated documentation:
* Swagger specification => [OpenAPI spec (OAS)](https://swagger.io/specification/)
* Converting inline code comments to OAS using the [oas tool](https://openap.is/)

There seems to be a lot of tools converting from OAS to other readable formats:
* https://openapi.tools/#documentation
* Most generate complete webpages rather than a simple markdown file
* A custom script could be used to create readme documentation from the OAS format

**Comment by aalu1418** [comment]
Current configuration/tools:
Using [swagger-jsdoc](https://www.npmjs.com/package/swagger-jsdoc) v6.x as a CLI tool to build OpenAPI spec from code comments.

Command to run:
```
npx swagger-jsdoc@6 -d swaggerDefinition.json $(find ./src -type f)
```

Example in the `coingecko` source adapter in the [feature/autogen-docs](https://github.com/smartcontractkit/external-adapters-js/tree/feature/autogen-docs) branch.

Next tasks:
- [ ] Generate `definition.json` file automatically for the adapter
- [ ] Create proper documentation structure in jsdoc comments (check for inserting environment variable parameters)
- [ ] Front-end visualization of documentation (converting OAS structure to hosted webpages?)

**Comment by aalu1418** [comment]
New working branch: https://github.com/smartcontractkit/external-adapters-js/tree/feature/autogen-docs-2
Trying to pull parameters directly out of EAs
- [x] Pull endpoint parameters from `./endpoint/*.ts` files
- [ ] Pull possible endpoints from `adapter.ts`
- [ ] Pull environment variables from `config.ts`

For full deployment, requires changes to existing EAs to export the necessary parameters

**Comment by boxhock** [comment]
@austinborn is owning autogenerating documentation on separate stories now
